version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:3
    ports:
      - '8200:8080'
      - '4443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_EMAIL=castanedadf@gmail.com
      - MOODLE_SITE_NAME=ZENYA
      - MOODLE_HOST=zenya.site
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_SMTP_HOST=smtp.hostinger.com
      - MOODLE_SMTP_PORT=587
      - MOODLE_SMTP_USER=moodle@zenya.mx
      - MOODLE_SMTP_PASSWORD=Zenya_2022@
      - MOODLE_SMTP_PROTOCOL=tls
      - PHP_POST_MAX_SIZE=600M
      - PHP_UPLOAD_MAX_FILESIZE=600M
      - PHP_MAX_EXECUTION_TIME=600
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
